---
- name: Install Docker Components
  package:
    name:
      - "docker.io"
      - "docker-compose"
    state: present

- name: Ensure Docker Service Is Enabled And Started
  service:
    name: docker
    state: started
    enabled: yes

- name: Add Ubuntu User To Docker Group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Create monitoring directory
  file:
    path: /opt/monitoring
    state: directory

- name: Copy Prometheus & Grafana Config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: prometheus.yml.j2
      dest: /opt/monitoring/prometheus.yml
    - src: grafana-datasource.yml.j2
      dest: /opt/monitoring/grafana-datasource.yml
    - src: grafana-dashboards.yml.j2
      dest: /opt/monitoring/grafana-dashboards.yml

- name: Create Grafana dashboards directory
  file:
    path: /opt/monitoring/dashboards
    state: directory

- name: Download Node Exporter dashboard
  get_url:
    url: https://grafana.com/api/dashboards/1860/revisions/37/download
    dest: /opt/monitoring/dashboards/node-exporter.json

- name: Copy Over Docker / cAdvisor dashboard
  copy:
    src: ../files/docker-dashboard.json
    dest: /opt/monitoring/dashboards/docker-dashboard.json

- name: Copy Docker Compose
  copy:
    src: ../files/docker-compose.yml
    dest: /opt/monitoring/docker-compose.yml

- name: Build and Start Containers
  command:
    cmd: "docker-compose up -d"
    chdir: /opt/monitoring

- name: Check Container Status
  command:
    cmd: "docker ps -a"
  register: docker_status

- name: Display Container Feedback
  debug:
    var: docker_status.stdout_lines

