- name: Install Docker Packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - docker.io
    - docker-compose

- name: Create monitoring directory
  file:
    path: /opt/monitoring
    state: directory

- name: Copy Prometheus & Grafana Config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: prometheus.yml.j2
      dest: /opt/monitoring/prometheus.yml
    - src: grafana-datasource.yml.j2
      dest: /opt/monitoring/grafana-datasource.yml
  
- name: Copy Docker Compose
  copy:
    src: ../files/docker-compose.yml
    dest: /opt/monitoring/docker-compose.yml

- name: Build and Start Containers
  command:
    cmd: "docker-compose up -d"
    chdir: /opt/monitoring
