---
- name: Install Docker Components
  package:
    name:
      - "docker.io"
      - "docker-compose"
    state: present

- name: Ensure Docker Service Is Enabled And Started
  service:
    name: docker
    state: started
    enabled: yes

- name: Add Ubuntu User To Docker Group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Create Log Directories
  file:
   path: "{{ item }}"
   state: directory
  loop:
    - "/opt/promtail"
    - "/var/lib/promtail"

- name: Copy Over Nginx Files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: ubuntu
    force: true
  loop:
    - src: "../files/docker-compose.yml"
      dest: "/home/ubuntu/docker-compose.yml"
    - src: "../files/nginx.conf"
      dest: "/home/ubuntu/nginx.conf"
    - src: "../files/promtail-config.yml"
      dest: "/home/ubuntu/promtail-config.yml"

- name: Stop Existing Docker Containers
  command:
    cmd: "docker-compose down"
    chdir: "/home/ubuntu"

- name: Run Docker Compose
  command:
    cmd: "docker-compose up -d"
    chdir: "/home/ubuntu"
