---
- name: Terraform Plan
  command:
    cmd: terraform plan -no-color
    chdir: /home/jared/learning-terraform/terraform
  register: terraform_plan

- name: Debug Terraform
  debug:
    var: terraform_plan.stdout

- name: Terraform Apply
  command:
    cmd: terraform apply --auto-approve
    chdir: /home/jared/learning-terraform/terraform

- name: Refresh Inventory
  meta: refresh_inventory
