FROM jenkins/inbound-agent:latest

USER root

ARG DEBIAN_FRONTEND=noninteractive
ARG TERRAFORM_VERSION=1.15.2

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y \
    ca-certificates \
    curl \
    unzip \
    git \
    jq \
    python3 \
    python3-pip \
    ansible \
    openssh-client \
    make \
    python3-boto3


RUN rm -rf /var/lib/apt/lists/*


RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install
RUN rm -rf aws awscliv2.zip

RUN curl -fsSL "https://releases.hashicorp.com/terraform/1.15.2/terraform_1.15.2_linux_amd64.zip" \
    -o /tmp/terraform.zip \
    && unzip /tmp/terraform.zip -d /usr/local/bin \
    && rm /tmp/terraform.zip


RUN mkdir -p /home/jenkins/agent
RUN chown -R jenkins:jenkins /home/jenkins
RUN mkdir /home/jenkins/.ssh
RUN chown -R jenkins:jenkins /home/jenkins/.ssh

USER jenkins
