---
services:
    database:
        image: mysql:8.0
        container_name: database
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: "directus"
            MYSQL_USER: "user"
            MYSQL_ROOT_PASSWORD: "password123"
            MYSQL_PASSWORD: "password123"
        volumes:
            - ./mysql-data:/var/lib/mysql
            - ./init-admin.sql:/docker-entrypoint-initdb.d/init-admin.sql

    cadvisor:
      image: gcr.io/cadvisor/cadvisor
      container_name: cadvisor
      restart: unless-stopped
      ports:
        - "8080:8080"
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:ro
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
