services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /opt/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: "Jazzar101"
      GF_SECURITY_ADMIN_PASSWORD: "password123!"
      GF_USERS_ALLOW_SIGN_UP: "false"
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
      - /opt/monitoring/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - /opt/monitoring/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - /opt/monitoring/dashboards/:/etc/grafana/provisioning/dashboards-json:ro

    loki:
      image: grafana/loki:latest
      container_name: loki
      restart: always
      command: -config.file=/etc/loki/loki-config.yml:ro
      volumes:
        - ./loki/loki-config.yml:/etc/loki/loki-config.yml:ro
        - loki-data:/loki
      ports:
        - "3100:3100"

volumes:
  grafana-data:
  loki-data:
