---
- name: Update All Machines
  hosts: all
  become: true
  tasks:
    - name: Wait For All Instances SSM
      command: echo "Ready"
      register: result
      retries: 10
      delay: 5
      until: result.rc == 0

    - name: Update And Upgrade Apt Packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

- name: Install Nginx Proxy
  hosts: nginx
  become: yes
  tasks:
    - name: Configure Nginx Proxy
      include_role:
        name: configure_nginx
        tasks_from: main.yml

- name: Deploy Services
  hosts: web_app, database
  become: true
  tasks:
    - name: Call Deploy Services Roles
      include_role:
        name: deploy_services
        tasks_from: main.yml

- name: Install Metrics Exporters
  hosts: web_app, database
  become: true
  tasks:
    - name: Run Install Exporters Role
      include_role:
        name: install_exporters
        tasks_from: main.yml

- name: Setup Monitoring
  hosts: monitoring
  become: true
  tasks:
    - name: Setup Monitoring Services
      include_role: 
        name: setup_monitoring
        tasks_from: main.yml
      
- name: Run Tests
  hosts: tests
  become: true
  tasks:
    - name: Check EC2 Instances
      describe_instances:
#        aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
#       aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
#        region: "eu-west-2" 
      register: instance_details
    
    - name: Display EC2 Instances
      debug:
        var: instance_details

    - name: Run Tests
      include_role:
        name: run_tests
        tasks_from: main.yml

