---
services:
  app:
    image: directus/directus
    container_name: app
    restart: always
    environment:
      DB_CLIENT: "mysql"
      DB_HOST: "10.0.2.214"
      DB_PORT: 3306
      DB_USER: "user"
      DB_PASSWORD: "password123"
      DB_DATABASE: "directus"

      KEY: "mykey"
      SECRET: "mysecret"

      ADMIN_EMAIL: "admin@admin.com"
      ADMIN_PASSWORD: "password123"
    volumes:
      - ./strapi-data:/srv/data
    ports:
      - "8055:8055"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
 
