---
services:
    database:
        image: mysql:8.0
        container_name: database
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: "directus"
            MYSQL_USER: "user"
            MYSQL_ROOT_PASSWORD: "password123"
            MYSQL_PASSWORD: "password123"
        volumes:
            - ./mysql-data:/var/lib/mysql
            - ./init-admin.sql:/docker-entrypoint-initdb.d/init-admin.sql
