---
- name: Install applications in Docker on AWS VMs
  hosts: all
  become: true
  tasks:
  - name: Update And Upgrade Apt Packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400

  - name: Install Docker Components
    package:
      name:
        - "docker.io"
        - "docker-compose"
      state: present

  - name: Ensure Docker Service Is Enabled And Started
    service:
      name: docker
      state: started
      enabled: yes

  - name: Add Ubuntu User To Docker Group
    user:
      name: ubuntu
      groups: docker
      append: yes

  - name: Copy Over Database Files
    copy:
      src: "{{ item.src }}"
      dest: "/home/ubuntu/{{ item.dest }}"
      owner: ubuntu
      force: true
    loop:
      - src: ../files/database-docker-compose.yml
        dest: docker-compose.yml
    when: inventory_hostname in groups['database']

  - name: Copy Over Web_App Files
    copy:
      src: "{{ item.src }}"
      dest: "/home/ubuntu/{{ item.dest }}"
      owner: ubuntu
      force: true
    loop:
      - src: ../files/web-app-docker-compose.yml
        dest: docker-compose.yml
      - src: ../files/nginx.conf
        dest: nginx.conf
    when: inventory_hostname in groups['web_app']

  - name: Copy Over Test Files
    copy:
      src: ../files/run_tests.py
      dest: /home/ubuntu/
      owner: ubuntu
      force: true
    when: inventory_hostname in groups['tests']

  - name: Run Docker Commands
    block:
      - name: Stop Existing Docker Containers
        command:
          cmd: "docker-compose down"
          chdir: "/home/ubuntu"

      - name: Run Docker Compose
        command:
          cmd: "docker-compose up -d"
          chdir: "/home/ubuntu"
    when: inventory_hostname in groups['web_app'] or inventory_hostname in groups['database']

