---
- name: Run API Tests Against Web App
  hosts: tests
  become: true
  tasks:
  - name: Install Python3
    package:
      name:
        - "python3"
      state: present

  - name: Run API Python Tests
    command:
      cmd: python3 run_tests.py
      chdir: /home/ubuntu/

  vars:
    content_api_key: "${content_api_key}"    
